Repository AY2021S1-CS2113-T14-3/tp, pull requests merged in 2020-11, with the labels that each got.

#146 Refactor Model class
  docs/diagrams/ArchitectureDiagram.pptx
  docs/images/ArchitectureDiagram.png
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/AddRecurringCommand.java
  src/main/java/seedu/duke/commands/BorrowCommand.java
  src/main/java/seedu/duke/commands/ByeCommand.java
  src/main/java/seedu/duke/commands/CalendarCommand.java
  src/main/java/seedu/duke/commands/CategoryCommand.java
  src/main/java/seedu/duke/commands/ClearCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/CommandCreator.java
  src/main/java/seedu/duke/commands/DateCommand.java
  src/main/java/seedu/duke/commands/DeductCommand.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/commands/DoneCommand.java
  src/main/java/seedu/duke/commands/FindCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/commands/ListModuleCommand.java
  src/main/java/seedu/duke/commands/MakeFolderCommand.java
  src/main/java/seedu/duke/commands/ReturnCommand.java
  src/main/java/seedu/duke/commands/SetCommand.java
  src/main/java/seedu/duke/model/ListType.java
  src/main/java/seedu/duke/model/Model.java
  src/main/java/seedu/duke/model/item/Book.java
  src/main/java/seedu/duke/model/item/Credit.java
  src/main/java/seedu/duke/model/item/Item.java
  src/main/java/seedu/duke/model/item/Link.java
  src/main/java/seedu/duke/model/item/Module.java
  src/main/java/seedu/duke/model/item/Task.java
  src/main/java/seedu/duke/model/itemlist/BookList.java
  src/main/java/seedu/duke/model/itemlist/CreditList.java
  src/main/java/seedu/duke/model/itemlist/ItemList.java
  src/main/java/seedu/duke/model/itemlist/LinkList.java
  src/main/java/seedu/duke/model/itemlist/ModuleList.java
  src/main/java/seedu/duke/model/itemlist/TaskList.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
  src/test/java/seedu/duke/commands/CategoryCommandTest.java
  src/test/java/seedu/duke/commands/DateCommandTest.java
  src/test/java/seedu/duke/commands/DeleteCommandTest.java
  src/test/java/seedu/duke/commands/ListCommandTest.java
  src/test/java/seedu/duke/commands/SetCommandTest.java
  src/test/java/seedu/duke/task/TaskTest.java
Labels: priority.High

#149 Fix ModuleList bugs
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/CommandCreator.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/item/Module.java
  src/main/java/seedu/duke/model/itemlist/ItemList.java
  src/main/java/seedu/duke/model/itemlist/ModuleList.java
  src/test/java/seedu/duke/model/item/ModuleTest.java
Labels: type.Bug, type.Documentation, type.Enhancement, type.ModuleList

#150 Fix Parser bugs
  src/main/java/seedu/duke/parser/Parser.java
Labels: type.Bug, type.Documentation, type.Parser

#151 Bug fix for wrong message and invalid url
  build.gradle
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/item/Link.java
  src/main/java/seedu/duke/model/itemlist/BookList.java
  src/main/java/seedu/duke/model/itemlist/ItemList.java
  src/main/java/seedu/duke/model/itemlist/LinkList.java
  src/main/java/seedu/duke/model/itemlist/TaskList.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, type.Documentation, type.LinksList

#158 Added Duplicated Borrow
  .gitignore
  docs/UserGuide.md
  docs/team/muhammadhozefa.md
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/ClearCommand.java
  src/main/java/seedu/duke/commands/CommandCreator.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/item/Book.java
  src/main/java/seedu/duke/model/item/Module.java
  src/main/java/seedu/duke/model/itemlist/BookList.java
  src/main/java/seedu/duke/model/itemlist/ItemList.java
  src/main/java/seedu/duke/model/itemlist/ModuleList.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Documentation, type.Enhancement

#159 Fix TaskList issues
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/AddRecurringCommand.java
  src/main/java/seedu/duke/common/Messages.java
  text-ui-test/EXPECTED.TXT
Labels: severity.Low, type.Bug, type.Documentation, type.TaskList

#160 Allow adding incomplete modules
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/CommandCreator.java
  src/main/java/seedu/duke/commands/DoneCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/item/Module.java
  src/main/java/seedu/duke/model/itemlist/ItemList.java
  src/main/java/seedu/duke/model/itemlist/ModuleList.java
  src/main/java/seedu/duke/storage/Storage.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Documentation, type.Enhancement, type.ModuleList, type.Task

#163 Updated Muhammad PPP
  docs/team/muhammadhozefa.md
Labels: type.Documentation

#164 Add portfolio link in AboutUs
  docs/AboutUs.md
  docs/team/johndoe.md
  docs/team/muhammadhozefa.md
  docs/team/template.md
Labels: type.Documentation

#166 Updated flag notes in UG
  docs/UserGuide.md
Labels: type.Documentation

#167 Improve docs
  docs/AboutUs.md
  docs/team/iamchenjiajun.md
Labels: type.Documentation

#172 Slight editing to UG
  docs/UserGuide.md
  src/main/java/seedu/duke/model/item/Link.java
Labels: type.Documentation

#173 Update TOC
  docs/UserGuide.md
  docs/_config.yml
Labels: type.Documentation

#174 Remove credit
  docs/team/muhammadhozefa.md
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/CommandCreator.java
  src/main/java/seedu/duke/commands/DeductCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/ListType.java
  src/main/java/seedu/duke/model/item/Credit.java
  src/main/java/seedu/duke/model/itemlist/CreditList.java
  src/main/java/seedu/duke/model/itemlist/LinkList.java
  src/main/java/seedu/duke/model/itemlist/ModuleList.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/Storage.java
  text-ui-test/EXPECTED.TXT
Labels: type.Documentation, type.ModuleList

#177 Edit take note
  docs/UserGuide.md
Labels: type.Documentation

#178 Refactor Test Code
  src/test/java/seedu/duke/commands/AddCommandTest.java
  src/test/java/seedu/duke/commands/CommandTest.java
  src/test/java/seedu/duke/commands/DateCommandTest.java
  src/test/java/seedu/duke/commands/SetCommandTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
  src/test/java/seedu/duke/task/TaskTest.java
Labels: severity.Medium

#181 Fix Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/DukeSequenceDiagram.puml
  docs/diagrams/StorageSequenceDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/DukeSequenceDiagram.png
  docs/images/StorageSequenceDiagram.png
Labels: type.Documentation

#185 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Documentation

#184 DG user stories
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/muhammadhoze.md
  src/main/java/seedu/duke/commands/AddCommand.java
Labels: type.Documentation

#189 Update documentation
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/ListModuleCommand.java
  src/main/java/seedu/duke/model/ListType.java
  src/main/java/seedu/duke/model/Model.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: type.Documentation

#190 DG update
  docs/DeveloperGuide.md
Labels: type.Documentation

#192 Fix User Stories
  docs/DeveloperGuide.md
Labels: type.Documentation

#196 Update documentation
  docs/DeveloperGuide.md
  docs/team/iamchenjiajun.md
Labels: type.Documentation

#197 Add profile picture
  docs/AboutUs.md
  docs/displayPictures/ChenJiaJunPhoto.jpg
  docs/team/iamchenjiajun.md
Labels: type.Documentation

#201 Update Expenses section in User Guide
  docs/UserGuide.md
  docs/team/muhammadhoze.md
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/ByeCommand.java
  src/main/java/seedu/duke/commands/CalendarCommand.java
  src/main/java/seedu/duke/commands/CategoryCommand.java
  src/main/java/seedu/duke/commands/ClearCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/CommandCreator.java
  src/main/java/seedu/duke/commands/DateCommand.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/commands/DeleteExpenseCommand.java
  src/main/java/seedu/duke/commands/DoneCommand.java
  src/main/java/seedu/duke/commands/FindCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/commands/ListExpenseCommand.java
  src/main/java/seedu/duke/commands/ListModuleCommand.java
  src/main/java/seedu/duke/commands/MakeFolderCommand.java
  src/main/java/seedu/duke/commands/SetCommand.java
  src/main/java/seedu/duke/commands/SpendCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/item/Module.java
  text-ui-test/EXPECTED.TXT
Labels: type.Documentation

#204 fixes to PPP
  docs/UserGuide.md
  docs/team/muhammadhoze.md
  src/main/java/seedu/duke/DukeException.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/common/Utils.java
  src/main/java/seedu/duke/model/ListType.java
  src/main/java/seedu/duke/model/item/Expense.java
  src/main/java/seedu/duke/model/item/Item.java
  src/main/java/seedu/duke/model/item/Link.java
  src/main/java/seedu/duke/model/item/Module.java
  src/main/java/seedu/duke/model/item/Task.java
  src/main/java/seedu/duke/model/item/TotalExpenseType.java
  src/main/java/seedu/duke/model/itemlist/ExpenseList.java
  src/main/java/seedu/duke/model/itemlist/LinkList.java
  src/main/java/seedu/duke/model/itemlist/TaskList.java
  src/main/java/seedu/duke/storage/Storage.java
Labels: type.Documentation

#206 Final updates to PPP
  docs/team/muhammadhoze.md
Labels: type.Documentation

#209 Update User Guide
  docs/UserGuide.md
  expenses.txt
Labels: type.Documentation

#211 Bug Fixes
  docs/UserGuide.md
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/common/Utils.java
  src/main/java/seedu/duke/model/item/Module.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/model/item/ModuleTest.java
  src/test/java/seedu/duke/model/item/TaskTest.java
Labels: priority.High, severity.High, type.Bug, type.Documentation

#215 Update DG, fix minor Parser bug
  docs/DeveloperGuide.md
  docs/diagrams/ParserSequenceDiagram.puml
  docs/images/ParserSequenceDiagram.png
  docs/team/iamchenjiajun.md
  src/main/java/seedu/duke/parser/Parser.java
Labels: type.Documentation

#222 Fix errors with Commands
  src/main/java/seedu/duke/commands/CommandCreator.java
  src/main/java/seedu/duke/model/itemlist/TaskList.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: severity.Medium, type.Bug
